
steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - -c
      - |
        echo 'ENV: '${_SB_ENV}
        sed -i "s|_SB_ENV|${_SB_ENV}|g" app.yaml
        sed -i "s|_BUILD_TIME|`date`|g" ./src/main/resources/application.yaml
        sed -i "s|_COMMIT_ID|${COMMIT_SHA}|g" ./src/main/resources/application.yaml
        sed -i "s|_BRANCH_NAME|${BRANCH_NAME}|g" ./src/main/resources/application.yaml
        cat app.yaml # you can now see the secret value inserted as the env variable
        gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy
timeout: '1600s'
