app:
  name: CanaWeb-API
  description: ${app.name} is running in DEFAULT.

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
  cloud:
    gcp:
      firestore:
        enabled: true
        project-id: dev-canaweb-firestore

  level:
    org:
      springframework:
        web:
          cors:
            reactive:
              DefaultCorsProcessor: DEBUG
---
spring:
  config:
    activate:
      on-profile: local
app:
  name: CanaWeb-API
  description: ${app.name} is running in LOCAL.

---
spring:
  config:
    activate:
      on-profile: prod
app:
  name: CanaWeb-API
  description: ${app.name} is running in PROD.


